//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.SQL
{
    using System;
    
    public partial class GetSubjectById_Result1
    {
        public long id { get; set; }
        public string name { get; set; }
        public string acronym { get; set; }
        public long courseid { get; set; }
        public long rcb { get; set; }
        public long rub { get; set; }
        public System.DateTime rct { get; set; }
        public System.DateTime rut { get; set; }
    }
}
