//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaper
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Html { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public long RCB { get; set; }
        public long RUB { get; set; }
        public System.DateTime RCT { get; set; }
        public System.DateTime RUT { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Marks { get; set; }
        public string Json { get; set; }
        public Nullable<long> ExaminationId { get; set; }
        public string Time { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
    
        public virtual Examination Examination { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
